version: '3'
services:
  nginx:
    container_name: 'nginx'
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ${REGISTRY_HOST}/named-web-nginx
    ports:
      - '80:80'
    depends_on:
      - node
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  node:
    container_name: 'node'
    build:
      context: ./node
      dockerfile: Dockerfile
    image: ${REGISTRY_HOST}/named-web-node
    ports:
      - '8000:8000'
